# This is a basic workflow to help you get started with Actions

name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/885475882644/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'appengine-vivek@third-current-338811.iam.gserviceaccount.com'
        token_format: 'access_token'

      
    - name: 'Access secret'
      run: |-
          curl --request POST \
          'https://dialogflow.googleapis.com/v2/projects/third-current-338811/agent:restore?' \
          --header 'Authorization: Bearer ${{steps.auth.outputs.access_token}}' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data '{"agentUri":"gs://dialogflowbucketmigration/FlightAssistant.zip"}' \
          --compressed
    
    - name: 'Access secret'
      run: |-
          curl --request PATCH \
          'https://dialogflow.googleapis.com/v2/projects/third-current-338811/fulfillment?updateMask=husuhsuhsuh%2Cyuiyiu%2Cfsdjhsjdh`' \
          --header 'Authorization: Bearer ${{steps.auth.outputs.access_token}}' 




          
