# This is a basic workflow to help you get started with Actions

name: Deploy to App Engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
      
   
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/885475882644/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'appengine-vivek@third-current-338811.iam.gserviceaccount.com'
        token_format: 'access_token'
    
    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v0'
      with:
        secrets: |-
          token:projects/third-current-338811/secrets/serviceaccountkey

    - name: Create a Env file
      run:  |
        touch app_engine/.env
      #  touch ${{ inputs.artifact_name }}/app_engine/env.yaml  
      #  echo '${{ steps.secrets.outputs.token }}' >> app_engine/.env
      # echo '${{ steps.secrets.outputs.token }}' >> ${{ inputs.artifact_name }}/app_engine/env.yaml
        shell:  bash
    #    
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app_engine/app.yaml
       #deliverables: ${{ inputs.artifact_name }}/app_engine/app.yaml 
        version: v1
        project_id: 'third-current-338811'
      





          
